### ISSUE TITLE
Inconsistent results using TensorFlow lite on mobile devices

### ISSUE THREAD

**Issue by MahmoudMabrok** [AmrHendy/Arabic-Handwritten-Images-Recognition#2]

**Comment by MahmoudMabrok** [comment]
when i converted it to tensorflow lite and try to use it with mobile i get bad results 
all tried got wrong results

**Comment by MahmoudMabrok** [comment]
https://colab.research.google.com/drive/1Ng7jmPpHf-uJFqEuyHNpIDjtHEx9mo8T?usp=sharing

**Comment by AmrHendy** [comment]
I didn't try it using TensorFlow lite on any mobile devices, make sure of your conversion.
Check the demo and evaluation results of the current version.
